name: Code Quality

on: [push]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    container: rootproject/root:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: ./python/.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}