name: Code Quality

on: [push]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-16.04
    container: rootproject/root:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - uses: BSFishy/pip-action@v1
        with:
          packages: flake8
          requirements: requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit tests
        run: |
          bash ./test/data.sh
          python ./test/test_all.py